### ISSUE TITLE
RISDM can not deal with rasters that include NAs

### ISSUE THREAD

**Issue by duriber** [Scott-Foster/RISDM#3]
Hi Scott,

I think an issue of this package is that whenever the rasters that feed the data for _isdm_ contain NAs, such as water bodies in terrestrial analyses, the model is crashing with the error that I attach here.

![image](https://github.com/Scott-Foster/RISDM/assets/38749284/a69574ae-5dc8-429d-b408-661bde93e1ba)

**Comment by Scott-Foster** [comment]
Hi David,

Thanks for alerting me to this problem.  Is it possible to send through a minimum non-working example?  It makes things much easier to debug...

I have to wonder if the warning messages are not unrelated.  I haven't seen those warning messages before.  What is the class of your covarBrick?  Class of distForm?  Seems really odd that warnings (that seem like spatial stuff) are coming after a formula manipulation.

I'm back in the office tomorrow.  Might have time to look at this on the plane this afternoon, if I can get some more details.

Cheers

Scott

On Wed, 2023-07-12 at 00:49 -0700, David E. Uribe-Rivera wrote:

Hi Scott,

I think an issue of this package is that whenever the rasters that feed the data for isdm contain NAs, such as water bodies in terrestrial analyses, the model is crashing with the error that I attach here.

[image]<https://user-images.githubusercontent.com/38749284/252893918-a69574ae-5dc8-429d-b408-661bde93e1ba.png>

**Comment by WenHsiYang** [comment]
Hi Scott,

Has this issue been fixed? See files of [f3e6767598ac557e10f5d3044556db73fbc96111], [eef37b443f881fa82ecb92f99b71b9d32b6d25dc], [4cd7db6b1ad3664f13d65b722977f961fd5a9098] and [892368ce28203072e358c4fb072bf87528a6a9a8]
* R/isdm.model.matrix.R
* R/isdm_onGrid.R
* R/makeControl.R
* R/predict.isdm.R
* R/uniqueVarNames.R

**Comment by Scott-Foster** [comment]
I think that has been sorted.  Closed.

**Comment by Scott-Foster** [comment]
Closed.  I think that it has been dealt with.
